pool:
  vmImage: 'ubuntu-latest'

container: rust:1.35.0

steps:
- script: cargo build --release
  displayName: 'Build'

- script: cargo test --release --all
  displayName: 'Release tests'

- script: cargo build --release --benches
  displayName: 'Build all benches'
